//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posting
    {
        public int PostingID { get; set; }
        public string Title { get; set; }
        public int Company { get; set; }
        public string Description { get; set; }
        public string Skills { get; set; }
    
        public virtual Company Company1 { get; set; }
    }
}
