//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.CV = new HashSet<CV>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public System.DateTime RegisterDate { get; set; }

        [Required (ErrorMessage ="Kullanýcý adý boþ býrakýlamaz")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Þifre boþ býrakýlamaz")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Mail boþ býrakýlamaz")]
        public string Mail { get; set; }
        public Nullable<int> Profession { get; set; }
        public string Skills { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CV> CV { get; set; }
    }
}
